# Generated by Django 5.1.3 on 2024-12-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cliente_remove_pedido_endereco_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
