# Generated by Django 5.0.6 on 2024-12-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_itempedido_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
