# Generated by Django 5.0.6 on 2024-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_pedido_cliente'),
        ('app1', '0004_rename_data_pedido_pedido_data_criacao_and_more'),
    ]

    operations = [
    ]
